#!/usr/bin/env bash
# Manage the demo Jarvis instance — a second stack on this same checkout, with
# its own agent dir, used to produce clean screenshots. See demo/README.md.
#
#   bash demo/demo.sh seed     create demo/instance and demo/.env (once)
#   bash demo/demo.sh up       start it
#   bash demo/demo.sh down     stop it
#   bash demo/demo.sh logs     tail it
#   bash demo/demo.sh reset    wipe its state and re-seed (destructive)
set -euo pipefail

# Everything runs from the repo root: Compose resolves the relative paths in
# demo/docker-compose.yml against the project directory, which is the directory
# of the first -f.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

AGENT_DIR='demo/instance/agent'
ENV_FILE='demo/.env'
compose() { docker compose -p jarvis-demo -f docker-compose.yml -f demo/docker-compose.yml "$@"; }

rand() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# Reads one key out of the real .env without sourcing it (values may contain
# anything). Only used to borrow the Claude token and the timezone.
from_env() { [ -f .env ] && sed -n "s/^$1=//p" .env | head -1 || true; }

seed() {
  if [ -d "$AGENT_DIR" ] && [ "${1:-}" != '--force' ]; then
    echo "$AGENT_DIR already exists — 'reset' to wipe it, or pass --force." >&2
    exit 1
  fi

  mkdir -p "$AGENT_DIR/data" "$AGENT_DIR/workspace/apps" "$AGENT_DIR/workspace/uploads"

  # Only what the repo ships: CLAUDE.md, rules, the default skills, settings.
  # Nothing personal is tracked, so nothing personal can come along.
  git archive HEAD agent | tar -x --strip-components=1 -C "$AGENT_DIR"

  if [ ! -f "$ENV_FILE" ]; then
    {
      echo '# Demo instance — generated by demo/demo.sh, gitignored.'
      echo "JWT_SECRET=$(rand)"
      echo "INTERNAL_SECRET=$(rand)"
      # Borrowed so the demo boots straight into a usable chat instead of the
      # token step of the wizard. It is your subscription either way.
      echo "CLAUDE_CODE_OAUTH_TOKEN=$(from_env CLAUDE_CODE_OAUTH_TOKEN)"
      echo "TZ=$(from_env TZ)"
      echo 'ADMIN_EMAIL=demo@jarvis.local'
      echo "ADMIN_PASSWORD=demo-$(head -c 6 /dev/urandom | od -An -tx1 | tr -d ' \n')"
      echo 'SETUP_CODE=demo'
    } > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  fi

  echo "seeded $AGENT_DIR"
  echo "login:  $(sed -n 's/^ADMIN_EMAIL=//p' "$ENV_FILE") / $(sed -n 's/^ADMIN_PASSWORD=//p' "$ENV_FILE")"
}

case "${1:-}" in
  seed)  seed "${2:-}" ;;
  up)    compose up -d && echo "demo up → http://localhost:${DEMO_FRONTEND_PORT:-5273}" ;;
  down)  compose down ;;
  logs)  shift; compose logs -f --tail 100 "$@" ;;
  reset)
    read -rp "Delete $AGENT_DIR and everything in it? [y/N] " a
    [ "$a" = 'y' ] || exit 1
    compose down
    rm -rf "$AGENT_DIR"
    seed --force
    ;;
  *) sed -n '2,10p' "$0" >&2; exit 1 ;;
esac
